class FakeOrderItems {
  static final List<Map<String, dynamic>> list = [
    {
      'id': 'i0',
      'order': 'o3',
      'productName': 'Empanada de Cazon',
      'price': 3.0,
      'paid': false,
    },
    {
      'id': 'i1',
      'order': 'o3',
      'productName': 'Dog Chow 16kg ',
      'price': 96.20,
      'paid': false,
    },
    {
      'id': 'i2',
      'order': 'o3',
      'productName': 'Avant 18kg raza grande',
      'price': 84.04,
      'paid': false,
    },
    {
      'id': 'i3',
      'order': '12',
      'productName': 'Whiskas',
      'price': 3.0,
      'paid': false,
    },
    {
      'id': 'i4',
      'order': 'o4',
      'productName': 'Whiskas',
      'price': 1.50,
      'paid': false,
    },
    {
      'id': '123',
      'order': 'o4',
      'productName': 'asdas',
      'price': 3.0,
      'paid': false,
    },
    {
      'id': '123',
      'order': '12',
      'productName': 'asdas',
      'price': 3.0,
      'paid': false,
    },
    {
      'id': '123',
      'order': '12',
      'productName': 'asdas',
      'price': 3.0,
      'paid': false,
    },
    {
      'id': '123',
      'order': '12',
      'productName': 'asdas',
      'price': 3.0,
      'paid': false,
    },
    {
      'id': '123',
      'order': '12',
      'productName': 'asdas',
      'price': 3.0,
      'paid': false,
    },
    {
      'id': '123',
      'order': 'o2',
      'productName': 'asdas',
      'price': 3.0,
      'paid': false,
    },
    {
      'id': '123',
      'order': '12',
      'productName': 'asdas',
      'price': 3.0,
      'paid': false,
    },
    {
      'id': '123',
      'order': '12',
      'productName': 'asdas',
      'price': 3.0,
      'paid': false,
    },
    {
      'id': '123',
      'order': '12',
      'productName': 'asdas',
      'price': 3.0,
      'paid': false,
    },
  ];
}
